_meta:
  assumptions: UIA accessible; OCR for fallback only
  risks: OCR misorder and barge_in false positives
  alternatives: full_screen_ocr or disable_barge_in
  rationale: latency and privacy for 8GB VRAM
accessibility: 0
windows:
  stt: {ttl_ms: 4000, max: 10}
  screen: {ttl_ms: 3000, max: 5}
  text: {ttl_ms: 30000, max: 20}
  logs: {ttl_ms: 60000, max: 50}
focus_mode:
  roi: {scale: 1.0, debounce_ms: 120}
overlay:
  highlight_color: '#FFD700'
  dim: 0.18
ocr:
  engine: paddle
  languages: ['ko', 'en', 'ja', 'zh']
  topk: 5
  conf_threshold: 0.6
stt:
  backend: local
  model: small.en
voice:
  synonyms:
    stop: ['멈춰', '정지']
    next: ['다음', '넘겨']
    translate: ['번역', '해석']
  dangerous: ['삭제', '비우', '전송', '구매', '결제']
llm_budget:
  max_tokens: 2048
  timeout_ms: 600
  retry: 1
thinking_budget:
  nlu_intent: {default: 96, barge_in: 48}
  selection_disambiguation: {default: 256, barge_in: 128}
  translate_faithful: {default: 192, barge_in: 96}
  summarize_short: {default: 256, barge_in: 128}
  macro_plan: {default: 384, barge_in: 192}
answer_budget:
  nlu_intent: {default: 96, barge_in: 48}
  selection_disambiguation: {default: 128, barge_in: 64}
  translate_faithful: {default: 192, barge_in: 96}
  summarize_short: {default: 128, barge_in: 64}
  macro_plan: {default: 192, barge_in: 96}
ranking:
  weights: {text: 0.52, role: 0.18, near: 0.20, spatial: 0.10, disabled: -0.05}
  topk_for_llm: 5
translation:
  preserve: [NUMBER, DATE, URL, EMAIL, UNIT, CURRENCY, CODE]
  escalate_if:
    preserve_failed: '>=1'
    negations: '>=2'
    policy_keywords: '>=1'
barge_in:
  aec: true
  safety_gate_ms: 200
executor:
  clarify_once: true
  confirm_on_danger: true
  confirm_requires_wake: true
privacy:
  block_roles: ['password', 'secure']
  buffer_ttl_ms: 60000
  tokenization: true
profiles:
  low_vram:
    llm_budget: {max_tokens: 1200, snapshot: 2}
    ranking: {topk_for_llm: 12}
    ocr: {topk: 12}
# Checklist:
# - [x] Think Harder
# - [x] Think Deeper
# - [x] More Information
# - [x] Check Again
