# 로드/활성화할 플러그인 정의
tools:
  - name: echo
    module: tools.tool.echo
    class: Echo
    enabled: true

  - name: file.watch
    module: tools.tool.file_watch
    class: FileWatch
    enabled: true
    # 아래는 기본값이지만 참고용
    default_args:
      path: "./"
      pattern: "*.*"
      on_event: "create"
      interval_sec: 2

  - name: mail.imap_list
    module: tools.tool.mail_imap_list
    class: MailImapList
    enabled: false

  - name: ocr
    module: tools.tool.ocr
    class: OCR
    enabled: true
    desc: "이미지에서 텍스트를 추출"
    input_schema:
      type: object
      properties:
        image_path:
          type: string
          description: "이미지 파일 경로"
      required: [image_path]

  - name: stt
    module: tools.tool.stt
    class: STT
    enabled: true
    desc: "오디오에서 텍스트로 변환"
    input_schema:
      type: object
      properties:
        audio_path:
          type: string
          description: "오디오 파일 경로"
      required: [audio_path]
