llm_tools:    # 4B (빠른 플래너)
  endpoint: "http://127.0.0.1:1234/v1"
  model: "qwen/qwen3-4b-2507"
  api_key: "lm-studio"
  timeout_seconds: 60
  max_new_tokens: 2000
  temperature: 0.0

llm_chat:     # 14B (기본 채팅)
  endpoint: "http://127.0.0.1:1234/v1"
  model: "qwen3-14b"
  api_key: "lm-studio"
  timeout_seconds: 60
  max_new_tokens: 8096
  temperature: 0.2

llm_vision:   # 이미지가 포함된 대화용
  endpoint: "http://127.0.0.1:1234/v1"
  model: "gemma-3-12b-it-qat"
  api_key: "lm-studio"
  timeout_seconds: 60
  max_new_tokens: 8096
  temperature: 0.2

llm_summary:  # 20B (정확 요약/검색; 환각 적게)
  endpoint: "http://127.0.0.1:1234/v1"
  model: "openai/gpt-oss-20b"
  api_key: "lm-studio"
  timeout_seconds: 120
  max_new_tokens: 25000  # ✅ 웹검색 요약에 더 많은 토큰 활용
  temperature: 0.1

router:
  enable: true
  mode: "both"
  chat_triggers:
    - "(?i)\\bweather\\b"
    - "날씨|예보"
    - "(?i)\\bcnn\\b|\\bbbc\\b|\\bytm\\b"
    - "뉴스 ?요약"
    - "web ?search|웹 ?검색"

# ✅ 프록시 설정 완성
proxy:
  enable: true
  host: "127.0.0.1"
  port: 8350

ui:
  width: 640
  height: 500
  agent_handoff_on: true
  always_on_top: true
  show_on_start: true
  opacity: 0.92

# ✅ agent 설정 완성
agent:
  enable_health_watch: true
  health_url: "http://127.0.0.1:8765/health"
  event_url: "http://127.0.0.1:8765/event"
  health_interval_seconds: 5
  health_fail_quit_count: 6

# ✅ 디버그 설정
debug:
  overlay_echo_raw: true
  log_events: true
  connection_test: true

tools:
  # Launch local OCR script
  ocr.start:
    kind: "process"
    id: "ocr"
    command: "D:/jip/home-agent/.venv/Scripts/python.exe"
    args: ["D:/jip/home-agent/OCR/main.py"]
    cwd: "D:/jip/home-agent/OCR"
    no_console: true
    env:
      AGENT_EVENT_URL: "http://127.0.0.1:8350/plugin/event"
  ocr.stop:
    kind: "process_stop"
    id: "ocr"
    method: "terminate"

  # STT start/stop
    stt.start:
      kind: "process"
      id: "stt"
      command: "D:/jip/home-agent/.venv/Scripts/python.exe"
      args: ["D:/jip/home-agent/STT/VSRG-Ts-to-kr.py"]
      cwd: "D:/jip/home-agent/STT"
      no_console: true
      env:
        AGENT_EVENT_URL: "http://127.0.0.1:8350/plugin/event"
  stt.stop:
    kind: "process_stop"
    id: "stt"
    method: "terminate"

  # ✅ Enhanced Web Search with time-aware & high-volume settings
  web.search:
    kind: "process"
    id: "web"
    command: "D:/jip/home-agent/.venv/Scripts/python.exe"
    args: ["D:/jip/home-agent/Overlay/plugins/web_search.py",
           "--query", "{q}",
           "--topk", "{k}",
           "--summarize",
           "--post"]
    cwd: "D:/jip/home-agent/Overlay/plugins"
    no_console: false
    env:
      # ✅ Enhanced Web Search 환경변수
      AGENT_EVENT_URL: "http://127.0.0.1:8350/event"
      WEB_SEARCH_REGION: "ko-KR"
      WEB_SEARCH_LOCATION: "Busan, South Korea"
      WEB_SEARCH_DEFAULT_TOPK: "15"        # 기본 검색 결과 수 증가
      WEB_SEARCH_MAX_CHARS: "12000"       # LM Studio 토큰 활용
      WEB_SEARCH_MAX_SENTENCES: "10"      # 더 긴 요약
      WEB_SEARCH_MAX_FETCH: "6"           # 더 많은 페이지 수집
      # API 키들 (필요에 따라 설정)
      # BING_API_KEY: "your_bing_api_key_here"
      # SERPAPI_KEY: "your_serpapi_key_here"

llm:
  endpoint: "http://127.0.0.1:11434/v1"
  model: "qwen3-14b"  # 전역 폴백

llm_tools_small:
  endpoint: "http://127.0.0.1:11434/v1"
  model: "qwen/qwen3-4b-2507"

llm_tools_chat:
  endpoint: "http://127.0.0.1:11434/v1"
  model: "openai/gpt-oss-20b"



"plugins": {
"SecurityPlugin": {"enabled": True},
"SchedulePlugin": {"enabled": True, "timezone": "Asia/Seoul"},
"WebPlugin": {"enabled": True},
"KnowledgePlugin": {"enabled": True}
}