# Example config (process-based tools). Save as config.yaml next to overlay_tray_app_v3.py
llm:
  endpoint: "http://127.0.0.1:1234/v1"
  model: "qwen2.5-4b-instruct"
  api_key: ""
  timeout_seconds: 60

agent:
  health_url: "http://127.0.0.1:8765/health"
  event_url:  "http://127.0.0.1:8765/event"
  health_interval_seconds: 2
  health_fail_quit_count: 3

tools:
  # Launch local OCR script
  ocr.start:
    kind: "process"
    id: "ocr"
    command: "D:/jip/home-agent/.venv/Scripts/python.exe"
    args: ["D:/jip/home-agent/OCR/main.py"]
    cwd: "D:/jip/home-agent/OCR"
    no_console: true
  ocr.stop:
    kind: "process_stop"
    id: "ocr"
    method: "terminate"

  # Example: STT start/stop (adjust paths)
  stt.start:
    kind: "process"
    id: "stt"
    command: "D:/jip/home-agent/.venv/Scripts/python.exe"
    args: ["D:/jip/home-agent/STT/main.py"]
    cwd: "D:/jip/home-agent/STT"
    no_console: true
  stt.stop:
    kind: "process_stop"
    id: "stt"
    method: "terminate"

ui:
  opacity: 0.86
  width: 560
  height: 420
  font_family: "Malgun Gothic"
  font_size: 11
