limits:
  dedup_window_seconds: 3600
  max_queue_size: 1000
overlay:
  args: []
  cwd: Overlay
  enable: true
  python: .venv/Scripts/python.exe
  script: Overlay/overlay_app.py
policy:
  autonomy_level: auto
  batch_seconds: 300
server:
  host: 127.0.0.1
  port: 8765
sinks:
  log_file: agent_output.log
  toast: true
translate:
  api_key: ''
  endpoint: http://127.0.0.1:1234/v1
  max_refine_chars: 6500
  model: qwen/qwen3-4b-2507
  provider: lmstudio
  severity_threshold: 2
